# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download 469b Patch
        uses: robinraju/release-downloader@v1.2
        with:
          repository: "OldUnreal/UnrealTournamentPatches"
          tag: "v469b"
          fileName: "OldUnreal-UTPatch469b-Windows.zip"
          
      - name: Extract Patch
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: "OldUnreal-UTPatch469b-Windows.zip"
          pathTarget: .

      - name: Checkout NewCTF
        uses: actions/checkout@v2
        with:
          path: NewCTFv16/

      - name: Extract Necessary Resources
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: NewCTFv16/Build/BuildEnv.zip
          pathTarget: .

      # Runs a single command using the runners shell
      - name: Build NewCTF
        run: NewCTFv16/build.bat

      - name: Save UCC.log
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: ucc-output
          path: System/UCC.log

      - name: Save NewCTF Package
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: NewCTFv16
          path: |
            NewCTFv16/System/
            NewCTFv16/LICENSE
            NewCTFv16/README.md
